name: Hello World
author: Ali Alaa
description: Some description
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Matt
outputs:
  time:
    description: "The greeting time"
runs:
  using: "docker"
  image: "Dockerfile"
  # entrypoint:
  args:
    - ${{ inputs.who-to-greet }}
